### ISSUE TITLE
Use on QNAP system

### ISSUE THREAD

**Issue by therealspeez** [jlesage/docker-dupeguru#1]
First post on GitHub, first use of containers/docker so sorry if this is the wrong spot.

I'm trying to get this setup within Container station on my QNAP NAS box and I have it up and running - but my storage folder is empty and thus I can't see any of the data on my server to try and run the duplicate scan on. Within Container station there is a function to open a terminal (more like the run box on Windows, it's not a full command prompt screen just an input box). I have (tried) to run the reference commands with -v to set my main drive (named DataVol1) to the storage, but no dice.

Any experience or thoughts on how to get this mapped? This (sounds) like an awesome application ( use dupguru on my laptop frequently) but I'm not quite there yet.

Thanks

**Comment by jlesage** [comment]
I down have a QNAP NAS, but I think you can add a volume mapping by going to advanced settings of the container and then choose "Shared Folders".

**Comment by jlesage** [comment]
Closing the issue.  Feel free to re-open if you still have problems.

**Comment by cko-skverlag** [comment]
same Problem here - i can not choose the shared folders in container station advanced settings. thanks

**Comment by cko-skverlag** [comment]
Hi, i found the settings, but they don't allow to add a shared folder through the gui of the container station. I was able to get it done through the terminal using your code: 

`docker run -d     --name=dupeguru     -p 5800:5800     -v /docker/appdata/dupeguru:/config:rw     -v $HOME:/share/CACHEDEV1_DATA/Download:rw     jlesage/dupeguru`

but i still don't have access on the directory's content
<img width="1058" alt="dupeguru_folder" src="https://user-images.githubusercontent.com/6714708/51663715-d1274a00-1fb7-11e9-9be5-e27bfce765c8.png">
<img width="820" alt="advanced settings_port_containerstation" src="https://user-images.githubusercontent.com/6714708/51663717-d1bfe080-1fb7-11e9-8ee4-6c88ca47d9e5.png">
<img width="819" alt="advanced settings_share_containerstation" src="https://user-images.githubusercontent.com/6714708/51663718-d1bfe080-1fb7-11e9-8aa6-1e23236be739.png">

**Comment by jlesage** [comment]
I think the volume mapping in your `docker run` command is not correct.  Try to create the container like this:
```
docker run -d --name=dupeguru -p 5800:5800 -v /docker/appdata/dupeguru:/config:rw -v /share/CACHEDEV1_DATA/Download:/storage:rw jlesage/dupeguru
```
Then, in the container, you should see your files under `/storage`.
If you still don't see them, hen it's probably a permission issue.  Make sure to properly set `USER_ID` and `GROUP_ID` environment variables.  See https://github.com/jlesage/docker-dupeguru#usergroup-ids

**Comment by cko-skverlag** [comment]
Hi, thanks for your support. It was a problem with the permissions. I had to add the correct USER_ID and create a user for container station. THANKS!
