### ISSUE TITLE
Locales support

### ISSUE THREAD

**Issue by flying19880517** [jlesage/docker-dupeguru#12]
I usually use Chinese, but it doesn't display kanji.

<img width="544" alt="Snipaste_2022-12-23_23-38-55" src="https://user-images.githubusercontent.com/344444/209363629-0e2f2416-5db1-40d5-b17b-3aa410b6cf23.png">

**Comment by jlesage** [comment]
Did you set the `ENABLE_CJK_FONT` environment variable ?

**Comment by flying19880517** [comment]
Thanks, it works.

**Comment by flying19880517** [comment]
Close
