### ISSUE TITLE
Storage is there, but nothing found

### ISSUE THREAD

**Issue by TGda** [jlesage/docker-dupeguru#13]
Access are fine I can see the folders inside container sh
![image](https://user-images.githubusercontent.com/6738523/209476782-a36661c1-b2d7-4157-bdb7-804d9109dd8e.png)

But logs shows
![image](https://user-images.githubusercontent.com/6738523/209476424-00aab143-5d6c-415b-8da6-6d6a6c454bce.png)
and user interface
![image](https://user-images.githubusercontent.com/6738523/209476456-80bac823-ad2e-45d9-a83b-e2de313e1f19.png)

Apreciate your help guys

**Comment by jlesage** [comment]
Did you correctly set the `USER_ID` and `GROUP_ID` environment variables ?

**Comment by TGda** [comment]
Yes I did,
![image](https://user-images.githubusercontent.com/6738523/209480476-efdf001d-ca94-4704-bba1-d6346a85c180.png)
![image](https://user-images.githubusercontent.com/6738523/209480446-3ea8aec4-60fc-4c0f-93ab-0c05713ee54b.png)
![image](https://user-images.githubusercontent.com/6738523/209480405-181e788b-0874-43df-b9b4-1b3fde7b6078.png)

Weird... isnt it?

**Comment by jlesage** [comment]
`PUID`/`PGID` are not used.  You should set `USER_ID`/`GROUP_ID` instead.

**Comment by TGda** [comment]
And that got the job done.  Thanks.  My mistake on the variables.  I got that from this youtube guide
![image](https://user-images.githubusercontent.com/6738523/209482214-1920ba84-0e97-4aa7-910a-6005c7f8013e.png)
Thanks for the support

**Comment by jlesage** [comment]
You are welcome!
