### ISSUE TITLE
Increase Font Size?

### ISSUE THREAD

**Issue by DrPeterVC** [jlesage/docker-dupeguru#15]
I have previously used DupGuru on Windows and it has worked well for me.  I am now trying to use it on my Pi NAS using Docker in OMV with Portainer.

I have got it working (after some initial issues with GUID and PUID - now fixed).

BUT I can hardly read the screen as the font seems so small.  It is impossible to run on my Android tablet as it doesn't even let me zoom in so clicking on the menus is very hit and miss.  Even on my Win11 laptop using Edge it is still difficult to read.

Any suggestions?  I know there is an option to increase the font size in the comparison list - but it the menus I am struggling with.

**Comment by jlesage** [comment]
Can you share a screenshot of your screen ?

**Comment by DrPeterVC** [comment]
![Screenshot_20230220-101051_Chrome](https://user-images.githubusercontent.com/35200883/220078401-2052a95c-6a79-440f-ab41-628286cd3b69.jpg)

**Comment by DrPeterVC** [comment]
Above is a screenshot from my tablet in portrait mode.  I can obviously turn it and make it full screen - but the text is still very tiny still (and despite overriding the "allow zoom" in accessibility settings I cannot zoom it at all).  I am hoping that there is a simple setting I can change somewhere!  Sadly my eyesight isn't what it used to be :-(

**Comment by DrPeterVC** [comment]
Thanks for that.  I have been playing around with different screen sizes (simply changing the environment variables using Portainer) and trying the different scaling modes.

I am finding that using "remote scaling" with 1366*768 works best for me.

Initially "scaling none" seemed to work - but not sure why it won't anymore (despite changing the screen size back) ho hum.

I had been using a cli image deduplicator but as I have OMV with no gui it made visual comparisons very difficult.

So happy to close this issue now.  

Great software, well supported - which is more than can be said for many commercial products!

**Comment by jlesage** [comment]
Great, happy to see that you find this useful.

> Initially "scaling none" seemed to work - but not sure why it won't anymore (despite changing the screen size back) ho hum.

If you are testing with different devices at the same, activating the remote scaling on one device also affects other devices, because this feature dynamically changes, inside the container, the size of the app.
