### ISSUE TITLE
[Feature request] marked multiple files 

### ISSUE THREAD

**Issue by wiebereu** [jlesage/docker-dupeguru#17]
### Idea

Dupguru found more than 15.000 duplicate files. I was very happy cause finally i could clean up my storage volume. However, i was searching for an option to mark multiple files at once for deletion. I haven't found any. I have to select all 15.000 files one by one. That would be finished at the end of 2024 probably.

**Comment by wiebereu** [comment]
To be more precise i miss an option to mark all files at once or to mark from top to bottom with your Shift key just as in normal Windows or Linux

**Comment by jlesage** [comment]
> To be more precise i miss an option to mark all files at once or to mark from top to bottom with your Shift key just as in normal Windows or Linux

Yes this is already possible.  You click on the first item and then shift+click on the last idem and they will all be selected.

**Comment by wiebereu** [comment]
> > To be more precise i miss an option to mark all files at once or to mark from top to bottom with your Shift key just as in normal Windows or Linux
> 
> Yes this is already possible. You click on the first item and then shift+click on the last idem and they will all be selected.

No it doesn't work. You can select with shift but that is not the same as mark for deletion. If i do what you said and than select Mark for trash, i get the message that i haven't mark anything. 

What i was talking about is to be able to select multiple files in the left corner. You can see it on the image  i posted in the link [file selection](https://imgur.com/XhvIDiZl)


In order to delete file you have to select them in the left side of the screen . When you select a file the selection box turns blue. That is the only way you can mark for deletion. As i said you can't select multiple file at once.

**Comment by jlesage** [comment]
Once all files are highlighted in blue, you need to mark them.  This can be done by either:
* Pressing the space bar.
* Click the Mark->Mark Selected in menu.

**Comment by wiebereu** [comment]
> Once all files are highlighted in blue, you need to mark them. This can be done by either:
> 
>     * Pressing the space bar.
> 
>     * Click the Mark->Mark Selected in menu.
> 
> 
> (BTW the link you provided doesn't work)

I tested it and it works 

Thank you very much!
