### ISSUE TITLE
Inability to Select Which Duplicate Instance to Delete

### ISSUE THREAD

**Issue by Zeferin** [jlesage/docker-dupeguru#20]
Hello, I've been using dupeguru to identify and manage duplicate files. The tool is fantastic, but I've encountered an issue that impacts its usability for my use case.

Currently, when the tool identifies duplicates, it only allows me to mark a specific instance for deletion. I need to delete the other duplicate instance and not the one automatically selected by the tool. The problem is that the instance that I want to delete is not markable. 

Is there a way to mark for deletion the other instance of the duplicated file?

**Comment by jlesage** [comment]
You should be able to mark any instance of the duplicates.  Could you share an example (screenshot) of items that cannot be marked ?

**Comment by jlesage** [comment]
Did you define the `/volumeUSB4/` folder as the "reference" (`State` in the `Directories` tab) ?

**Comment by jlesage** [comment]
No change should be done to the directory marked as "Reference", meaning the instance of duplicates from this folder won't be removed.
You probably have to re-scan if you change the state of a directory.
Note that you can change which files are the reference, by right-clicking and selecting `Make Selected into Reference`.
