### ISSUE TITLE
Unable to run on Qnap NAS, 'exec format error'

### ISSUE THREAD

**Issue by krzacz0r** [jlesage/docker-dupeguru#3]
Starting the container installed from the docker hub gives the following error:

`standard_init_linux.go:185: exec user process caused "exec format error"`

This NAS has armv7l. 
Building the image leads to this:

```
...
Step 6/15 : RUN add-pkg         python3         py3-qt5         mesa-dri-swrast         dbus         &&     pip3 install         Send2Trash>=1.3.0         hsaudiotag3k>=1.1.3
 ---> Running in 71ad10da0d0d
standard_init_linux.go:185: exec user process caused "exec format error"
The command '/bin/sh -c add-pkg         python3         py3-qt5         mesa-dri-swrast         dbus         &&     pip3 install         Send2Trash>=1.3.0         hsaudiotag3k>=1.1.3' returned a non-zero code: 1
[~] #
```

Any help would be appreciated!

**Comment by jlesage** [comment]
This container image doesn't support arm.  Only support x86_64...

**Comment by CyberPK** [comment]
Please, can you create an arm version?

**Comment by jlesage** [comment]
Yes, this will eventually be possible.

**Comment by zaqrat** [comment]
> Yes, this will eventually be possible.

Has an ARM version been created?

**Comment by jlesage** [comment]
Not yet!
