### ISSUE TITLE
Build does not seem to work

### ISSUE THREAD

**Issue by SSoft7** [jlesage/docker-dupeguru#4]
I am getting the following error

```
copying build/lib.linux-x86_64-3.8/_block.cpython-38-x86_64-linux-gnu.so -> 
mv _block.cpython-38m*.so core/pe
[91mmv: can't rename '_block.cpython-38m*.so': No such file or directory
```
Can you test a build?

**Comment by SSoft7** [comment]
Okay, this issue is fixed in this commit https://github.com/arsenetar/dupeguru/commit/bd0f53bcbe463c48fe141b73af13542da36d82ba
I think it is a good idea to use commit rev as version.

**Comment by jlesage** [comment]
The Dockerfile is using the latest 4.0.4 release, so code to compile should always be the same.
I just tried a fresh build on my side and it terminated fine.

**Comment by jlesage** [comment]
Closing issue, please re-open if needed.
