### ISSUE TITLE
/Storage not found

### ISSUE THREAD

**Issue by killiampm** [jlesage/docker-dupeguru#5]
Good Afternoon.

i am running this docker on a synology NAS.

I have add the volumes (storage, config and trash), but when i start the docker, the application shows no folder¿?

Could you please help¿?

Thanks in advance.

**Comment by jlesage** [comment]
Could you provide more details about your container configuration/settings ?  What do you meed exactly by "the application shows no folder" ?  Folder is empty?

**Comment by killiampm** [comment]
Good Afternoon,

thanks for the answer.

- I have defined the columned in docker (storage, trash, config): 

![image](https://user-images.githubusercontent.com/42325404/103306968-30e1c780-4a0f-11eb-80d7-1b065f3fade6.png)

- Checked and modified the user_id and group_id in the environment variables

But when i start the docker, it show no folder or files...

![image](https://user-images.githubusercontent.com/42325404/103307423-44416280-4a10-11eb-8362-5f0b8ddf89d6.png)

Could you please help??

I have also tried to start docker container using bash, with the same result...

Thanks in advance,

Killiam

**Comment by jlesage** [comment]
You need to add folders by clicking the `+` button at the bottom-left of the window.  You should be able to see your folder/files under `/storage` in the selection window.

**Comment by killiampm** [comment]
Thanks a lot!!!!! It is working fine

**Comment by TGda** [comment]
Im having the same issue.
I used for the config my PUID and PGID from my Synology.  But still nothing is inside my Storage folder or trash folder no matter that thera are already files on the trash folder (put some to test it out) nor on my photo folder.
![image](https://user-images.githubusercontent.com/6738523/209416198-2a1a46af-5d1f-464c-9863-34c06bdaee13.png)
![image](https://user-images.githubusercontent.com/6738523/209416233-43254a3d-8b00-4976-9ba1-8734ef050d29.png)
![image](https://user-images.githubusercontent.com/6738523/209416273-82c38675-e7ef-4041-91d2-1486d22b48eb.png)
![image](https://user-images.githubusercontent.com/6738523/209416294-356603d2-f546-42b5-8abe-6a4467882ff9.png)
![image](https://user-images.githubusercontent.com/6738523/209416320-4efc504c-a255-45b7-b83c-54e8c8880bdd.png)
