### ISSUE TITLE
would you consider packaging czkawka?

### ISSUE THREAD

**Issue by zombiehoffa** [jlesage/docker-dupeguru#6]
I have been playing around with this: https://github.com/qarmin/czkawka

and it's really, really good and is being actively developed. The only reason I still have dupeguru around is your docker package lets me run dupeguru a lot closer to my data.

**Comment by jlesage** [comment]
It seems to be an easy one to do, I will check that :)

**Comment by jlesage** [comment]
Done :) 
https://github.com/jlesage/docker-czkawka
