### ISSUE TITLE
Remove Build command from docker-compose example

### ISSUE THREAD

**Issue by selner** [jlesage/docker-dupeguru#7]
As written, the docker-compose.yml example will not work for a user without removing the Build: .  command.   Suggest dropping that line so that it instead reads:

version: '3'
services:
  dupeguru:
    image: jlesage/dupeguru
    ports:
      - "5800:5800"
    volumes:
      - "/docker/appdata/dupeguru:/config:rw"
      - "$HOME:/storage:rw"

Second, less important, suggestion would be to use a relative path for the dupeguru config volume, such as:
      - "./config:/config:rw"

Thank you for providing this Docker image and for maintaining it.  It is much appreciated!

**Comment by jlesage** [comment]
Thanks for the feedback.  I will remove the build line from the example.

As for your second suggestion, I think that using a relative path may be more confusing for people, since it's not clear where exactly the directory on the host will be located.

**Comment by jlesage** [comment]
I'm not sure what you mean by "approved docker-compose.yml", but there is an example of a minimal compose file here: https://github.com/jlesage/docker-dupeguru#docker-compose-file.  Note that there are no mandatory environment variables, meaning that you can have a running container with dupeGuru accessible without any environment variable.  You only need to set the ones that are required for your specific needs.

Tell me if you more specific question.

For more details on how to set environment variables, the compose file format is documented here: https://docs.docker.com/compose/compose-file.  More specifically, here is the section about environment variables: https://docs.docker.com/compose/compose-file/#environment.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
