### ISSUE TITLE
standard_init_linux.go:219: exec user process caused: exec format error

### ISSUE THREAD

**Issue by zaqrat** [jlesage/docker-dupeguru#8]
I have:
QNAP TS-932PX
FIRMWARE: 4.5.4.1741
CPU: Annapurna Labs Alpine AL324 Quad-core ARM Cortex-A57 CPU @ 1.70GHz

I'm trying to create docker based container to run dupeguru and I get the error in the subject line.

I found a similar post from last year that has been closed, but wanted to follow-up and see if there is a work around/fix.

Thanks!

**Comment by jlesage** [comment]
The image doesn't support ARM yet.  Only x86_64.

**Comment by jlesage** [comment]
The image now supports ARM.
